"""create tables

Revision ID: b12cfc843f5c
Revises: 
Create Date: 2025-03-24 14:12:13.830896

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b12cfc843f5c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('availability', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activity_description'), 'activity', ['description'], unique=True)
    op.create_index(op.f('ix_activity_id'), 'activity', ['id'], unique=False)
    op.create_index(op.f('ix_activity_location'), 'activity', ['location'], unique=False)
    op.create_index(op.f('ix_activity_title'), 'activity', ['title'], unique=False)
    op.create_table('favorites',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('favorite_type', sa.String(), nullable=False),
    sa.Column('date_added', sa.Date(), nullable=False),
    sa.Column('activity_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['activity_id'], ['activity.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_favorites_date_added'), 'favorites', ['date_added'], unique=False)
    op.create_index(op.f('ix_favorites_favorite_type'), 'favorites', ['favorite_type'], unique=False)
    op.create_index(op.f('ix_favorites_id'), 'favorites', ['id'], unique=False)
    op.create_table('info',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('reservation_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('activity_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['activity_id'], ['activity.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_info_id'), 'info', ['id'], unique=False)
    op.create_index(op.f('ix_info_reservation_date'), 'info', ['reservation_date'], unique=False)
    op.create_index(op.f('ix_info_status'), 'info', ['status'], unique=False)
    op.create_table('reviews',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('date_rating', sa.Date(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('activity_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['activity_id'], ['activity.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reviews_date_rating'), 'reviews', ['date_rating'], unique=False)
    op.create_index(op.f('ix_reviews_description'), 'reviews', ['description'], unique=False)
    op.create_index(op.f('ix_reviews_id'), 'reviews', ['id'], unique=False)
    op.create_index(op.f('ix_reviews_rating'), 'reviews', ['rating'], unique=False)
    op.create_index(op.f('ix_reviews_user_id'), 'reviews', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reviews_user_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_rating'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_description'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_date_rating'), table_name='reviews')
    op.drop_table('reviews')
    op.drop_index(op.f('ix_info_status'), table_name='info')
    op.drop_index(op.f('ix_info_reservation_date'), table_name='info')
    op.drop_index(op.f('ix_info_id'), table_name='info')
    op.drop_table('info')
    op.drop_index(op.f('ix_favorites_id'), table_name='favorites')
    op.drop_index(op.f('ix_favorites_favorite_type'), table_name='favorites')
    op.drop_index(op.f('ix_favorites_date_added'), table_name='favorites')
    op.drop_table('favorites')
    op.drop_index(op.f('ix_activity_title'), table_name='activity')
    op.drop_index(op.f('ix_activity_location'), table_name='activity')
    op.drop_index(op.f('ix_activity_id'), table_name='activity')
    op.drop_index(op.f('ix_activity_description'), table_name='activity')
    op.drop_table('activity')
    # ### end Alembic commands ###
